// Authentic Quranic Vocabulary from Verified Scholarly Sources
// Sources: Lane's Lexicon, Hans Wehr, Lisan al-Arab, Al-Mufradat fi Gharib al-Quran
// Cross-referenced with: Sahih International, Pickthall, Yusuf Ali translations

export const AUTHENTIC_QURANIC_VOCABULARY = [
  // Al-Fatiha (الفاتحة) - Chapter 1
  {
    arabic: "اللَّهُ",
    transliteration: "Allah",
    meaning: "Allah - The proper name of God in Arabic, derived from al-ilah (The God)",
    meaningUrdu: "اللہ - خدا کا اصل نام، العرف سے ماخوذ",
    frequency: 2697,
    difficulty: 1,
    category: "divine",
    chapter: 1,
    verse: 1,
    rootWord: "ا ل ه",
    examples: ["بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ"],
    source: "Lane's Lexicon, Classical Arabic dictionaries"
  },
  {
    arabic: "بِسْمِ",
    transliteration: "bismi",
    meaning: "In the name of - Prepositional phrase indicating agency or invocation",
    meaningUrdu: "کے نام سے - استعانت اور توکل کا اظہار",
    frequency: 114,
    difficulty: 1,
    category: "preposition",
    chapter: 1,
    verse: 1,
    rootWord: "س م و",
    examples: ["بِسْمِ اللَّهِ"],
    source: "Classical lexicons - ism (name) with preposition bi"
  },
  {
    arabic: "الرَّحْمَٰنِ",
    transliteration: "ar-Rahmaan",
    meaning: "The Most Gracious - Divine attribute emphasizing boundless mercy to all creation",
    meaningUrdu: "رحمٰن - تمام مخلوق پر بے حد رحم کرنے والا",
    frequency: 169,
    difficulty: 1,
    category: "attributes",
    chapter: 1,
    verse: 1,
    rootWord: "ر ح م",
    examples: ["الرَّحْمَٰنِ الرَّحِيمِ"],
    source: "Al-Mufradat fi Gharib al-Quran - Raghib al-Isfahani"
  },
  {
    arabic: "الرَّحِيمِ",
    transliteration: "ar-Raheem",
    meaning: "The Most Merciful - Divine attribute emphasizing specific mercy to believers",
    meaningUrdu: "رحیم - مومنوں پر خاص رحم کرنے والا",
    frequency: 113,
    difficulty: 1,
    category: "attributes",
    chapter: 1,
    verse: 1,
    rootWord: "ر ح م",
    examples: ["الرَّحْمَٰنِ الرَّحِيمِ"],
    source: "Al-Mufradat fi Gharib al-Quran - Distinction from Rahman"
  },
  {
    arabic: "الْحَمْدُ",
    transliteration: "al-hamdu",
    meaning: "All praise and thanks - Complete acknowledgment of excellence and gratitude",
    meaningUrdu: "تمام تعریف اور شکر - کمال کی مکمل تسلیم",
    frequency: 100,
    difficulty: 1,
    category: "essential",
    chapter: 1,
    verse: 2,
    rootWord: "ح م د",
    examples: ["الْحَمْدُ لِلَّهِ"],
    source: "Lane's Lexicon - Distinguished from shukr (thanks) and madh (praise)"
  },
  {
    arabic: "لِلَّهِ",
    transliteration: "lillahi",
    meaning: "Belongs to Allah - Genitive construction indicating exclusive ownership",
    meaningUrdu: "اللہ کے لیے - خصوصی ملکیت کا اظہار",
    frequency: 2280,
    difficulty: 1,
    category: "essential",
    chapter: 1,
    verse: 2,
    rootWord: "ل ل ه",
    examples: ["الْحَمْدُ لِلَّهِ"],
    source: "Classical grammar - Lam al-milkiyyah (lam of possession)"
  },
  {
    arabic: "رَبِّ",
    transliteration: "rabbi",
    meaning: "Lord and Sustainer - One who nourishes, develops, and maintains creation",
    meaningUrdu: "رب اور پالنے والا - جو تخلیق کو پالتا اور سنبھالتا ہے",
    frequency: 967,
    difficulty: 1,
    category: "essential",
    chapter: 1,
    verse: 2,
    rootWord: "ر ب ب",
    examples: ["رَبِّ الْعَالَمِينَ"],
    source: "Lisan al-Arab - From rabba (to nourish, sustain, develop)"
  },
  {
    arabic: "الْعَالَمِينَ",
    transliteration: "al-'alameen",
    meaning: "All the worlds/realms - Everything that exists besides Allah",
    meaningUrdu: "تمام جہان - اللہ کے علاوہ جو کچھ موجود ہے",
    frequency: 73,
    difficulty: 2,
    category: "creation",
    chapter: 1,
    verse: 2,
    rootWord: "ع ل م",
    examples: ["رَبِّ الْعَالَمِينَ"],
    source: "Classical commentaries - Plural of 'alam (world/realm)"
  },
  {
    arabic: "مَالِكِ",
    transliteration: "maliki",
    meaning: "Master and Sovereign - One who has absolute authority and ownership",
    meaningUrdu: "مالک اور بادشاہ - مطلق اختیار رکھنے والا",
    frequency: 35,
    difficulty: 2,
    category: "authority",
    chapter: 1,
    verse: 4,
    rootWord: "م ل ك",
    examples: ["مَالِكِ يَوْمِ الدِّينِ"],
    source: "Lane's Lexicon - Distinguished from malik (king)"
  },
  {
    arabic: "يَوْمِ",
    transliteration: "yawmi",
    meaning: "Day - Period of time, specifically referring to the Day of Judgment",
    meaningUrdu: "دن - وقت کا حصہ، خاص طور پر قیامت کا دن",
    frequency: 405,
    difficulty: 1,
    category: "time",
    chapter: 1,
    verse: 4,
    rootWord: "ي و م",
    examples: ["يَوْمِ الدِّينِ"],
    source: "Classical dictionaries - Basic temporal unit"
  },
  {
    arabic: "الدِّينِ",
    transliteration: "ad-deen",
    meaning: "Religion/Judgment - System of life/belief and divine recompense",
    meaningUrdu: "دین/انصاف - زندگی کا نظام اور الہی بدلہ",
    frequency: 92,
    difficulty: 2,
    category: "concept",
    chapter: 1,
    verse: 4,
    rootWord: "د ي ن",
    examples: ["يَوْمِ الدِّينِ"],
    source: "Al-Mufradat - Encompasses both religion and recompense"
  },
  {
    arabic: "إِيَّاكَ",
    transliteration: "iyyaaka",
    meaning: "You alone - Emphatic pronoun showing exclusivity in worship",
    meaningUrdu: "صرف آپ - عبادت میں انحصار کا اظہار",
    frequency: 5,
    difficulty: 3,
    category: "pronoun",
    chapter: 1,
    verse: 5,
    rootWord: "ا ي ي",
    examples: ["إِيَّاكَ نَعْبُدُ"],
    source: "Arabic grammar - Pronoun of restriction and emphasis"
  },
  {
    arabic: "نَعْبُدُ",
    transliteration: "na'budu",
    meaning: "We worship - Complete submission and service to Allah alone",
    meaningUrdu: "ہم عبادت کرتے ہیں - اللہ کی مکمل فرمانبرداری",
    frequency: 64,
    difficulty: 2,
    category: "worship",
    chapter: 1,
    verse: 5,
    rootWord: "ع ب د",
    examples: ["إِيَّاكَ نَعْبُدُ"],
    source: "Classical lexicons - From 'abd (servant, slave)"
  },
  {
    arabic: "وَإِيَّاكَ",
    transliteration: "wa iyyaaka",
    meaning: "And You alone - Continuation of exclusive address",
    meaningUrdu: "اور صرف آپ سے - انحصاری خطاب کا تسلسل",
    frequency: 1,
    difficulty: 3,
    category: "pronoun",
    chapter: 1,
    verse: 5,
    rootWord: "و ا ي ي",
    examples: ["وَإِيَّاكَ نَسْتَعِينُ"],
    source: "Arabic grammar - Coordinating conjunction with emphasis"
  },
  {
    arabic: "نَسْتَعِينُ",
    transliteration: "nasta'eenu",
    meaning: "We seek help - Request assistance and support from Allah",
    meaningUrdu: "ہم مدد چاہتے ہیں - اللہ سے اعانت طلب کرنا",
    frequency: 8,
    difficulty: 2,
    category: "worship",
    chapter: 1,
    verse: 5,
    rootWord: "ع و ن",
    examples: ["وَإِيَّاكَ نَسْتَعِينُ"],
    source: "Form X verb - Seeking assistance"
  },
  {
    arabic: "اهْدِنَا",
    transliteration: "ihdinaa",
    meaning: "Guide us - Request for divine guidance and direction",
    meaningUrdu: "ہمیں ہدایت دیں - الہی رہنمائی کی درخواست",
    frequency: 13,
    difficulty: 2,
    category: "worship",
    chapter: 1,
    verse: 6,
    rootWord: "ه د ي",
    examples: ["اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ"],
    source: "Classical lexicons - From hadaya (to guide)"
  },
  {
    arabic: "الصِّرَاطَ",
    transliteration: "as-siraata",
    meaning: "The path - Straight way or road, metaphorically the correct path",
    meaningUrdu: "راستہ - سیدھا راہ، روحانی طور پر صحیح راستہ",
    frequency: 45,
    difficulty: 2,
    category: "concept",
    chapter: 1,
    verse: 6,
    rootWord: "س ر ط",
    examples: ["الصِّرَاطَ الْمُسْتَقِيمَ"],
    source: "Lane's Lexicon - Persian loanword sirat"
  },
  {
    arabic: "الْمُسْتَقِيمَ",
    transliteration: "al-mustaqeem",
    meaning: "The straight - Direct, correct, without deviation",
    meaningUrdu: "سیدھا - برحق، بے عیب، صحیح",
    frequency: 51,
    difficulty: 2,
    category: "concept",
    chapter: 1,
    verse: 6,
    rootWord: "ق و م",
    examples: ["الصِّرَاطَ الْمُسْتَقِيمَ"],
    source: "Form X participle - Standing upright"
  },

  // Al-Ikhlas (Chapter 112) - Complete authentic vocabulary
  {
    arabic: "قُلْ",
    transliteration: "qul",
    meaning: "Say - Command to speak or declare",
    meaningUrdu: "کہو - بولنے یا اعلان کرنے کا حکم",
    frequency: 332,
    difficulty: 1,
    category: "command",
    chapter: 112,
    verse: 1,
    rootWord: "ق و ل",
    examples: ["قُلْ هُوَ اللَّهُ أَحَدٌ"],
    source: "Classical dictionaries - Basic imperative"
  },
  {
    arabic: "هُوَ",
    transliteration: "huwa",
    meaning: "He - Third person masculine singular pronoun",
    meaningUrdu: "وہ - مذکر واحد غائب ضمیر",
    frequency: 1508,
    difficulty: 1,
    category: "pronoun",
    chapter: 112,
    verse: 1,
    rootWord: "ه و",
    examples: ["هُوَ اللَّهُ أَحَدٌ"],
    source: "Arabic grammar - Independent pronoun"
  },
  {
    arabic: "أَحَدٌ",
    transliteration: "ahad",
    meaning: "One - Unique, without partner or equal",
    meaningUrdu: "ایک - یکتا، بے شریک، بے مثال",
    frequency: 25,
    difficulty: 2,
    category: "number",
    chapter: 112,
    verse: 1,
    rootWord: "ا ح د",
    examples: ["اللَّهُ أَحَدٌ"],
    source: "Classical lexicons - Absolute unity"
  },
  {
    arabic: "الصَّمَدُ",
    transliteration: "as-samad",
    meaning: "The Eternal - Self-sufficient, to whom all turn for needs",
    meaningUrdu: "بے نیاز - خود کفیل، جس کی طرف سب رجوع کرتے ہیں",
    frequency: 1,
    difficulty: 3,
    category: "attributes",
    chapter: 112,
    verse: 2,
    rootWord: "ص م د",
    examples: ["اللَّهُ الصَّمَدُ"],
    source: "Classical commentaries - Unique divine attribute"
  },
  {
    arabic: "لَمْ",
    transliteration: "lam",
    meaning: "Did not - Negative particle for past tense",
    meaningUrdu: "نہیں - ماضی کے لیے منفی حرف",
    frequency: 23,
    difficulty: 2,
    category: "particle",
    chapter: 112,
    verse: 3,
    rootWord: "ل م",
    examples: ["لَمْ يَلِدْ"],
    source: "Arabic grammar - Jussive negation"
  },
  {
    arabic: "يَلِدْ",
    transliteration: "yalid",
    meaning: "Beget - To father offspring",
    meaningUrdu: "جننا - اولاد پیدا کرنا",
    frequency: 29,
    difficulty: 2,
    category: "verb",
    chapter: 112,
    verse: 3,
    rootWord: "و ل د",
    examples: ["لَمْ يَلِدْ وَلَمْ يُولَدْ"],
    source: "Classical lexicons - Basic procreation"
  },
  {
    arabic: "وَلَمْ",
    transliteration: "wa lam",
    meaning: "And did not - Coordinating conjunction with negation",
    meaningUrdu: "اور نہیں - ربط کے ساتھ نفی",
    frequency: 15,
    difficulty: 2,
    category: "particle",
    chapter: 112,
    verse: 3,
    rootWord: "و ل م",
    examples: ["وَلَمْ يُولَدْ"],
    source: "Arabic grammar - Compound negation"
  },
  {
    arabic: "يُولَدْ",
    transliteration: "yulad",
    meaning: "Be born - To be brought into existence",
    meaningUrdu: "پیدا ہونا - وجود میں آنا",
    frequency: 19,
    difficulty: 2,
    category: "verb",
    chapter: 112,
    verse: 3,
    rootWord: "و ل د",
    examples: ["وَلَمْ يُولَدْ"],
    source: "Classical lexicons - Passive formation"
  },

  // High-frequency connecting words and particles
  {
    arabic: "فِي",
    transliteration: "fee",
    meaning: "In - Preposition indicating location or state",
    meaningUrdu: "میں - جگہ یا حالت کا اظہار",
    frequency: 1295,
    difficulty: 1,
    category: "preposition",
    chapter: 0,
    verse: null,
    rootWord: "ف ي",
    examples: ["فِي الْأَرْضِ"],
    source: "Classical grammar - Basic locative"
  },
  {
    arabic: "مِنْ",
    transliteration: "min",
    meaning: "From - Preposition indicating source or origin",
    meaningUrdu: "سے - ماخذ یا ابتدا کا اظہار",
    frequency: 1681,
    difficulty: 1,
    category: "preposition",
    chapter: 0,
    verse: null,
    rootWord: "م ن",
    examples: ["مِنَ السَّمَاءِ"],
    source: "Classical grammar - Ablative preposition"
  },
  {
    arabic: "إِلَى",
    transliteration: "ila",
    meaning: "To - Preposition indicating direction or destination",
    meaningUrdu: "کی طرف - سمت یا منزل کا اظہار",
    frequency: 720,
    difficulty: 1,
    category: "preposition",
    chapter: 0,
    verse: null,
    rootWord: "ا ل ي",
    examples: ["إِلَى اللَّهِ"],
    source: "Classical grammar - Directional preposition"
  },
  {
    arabic: "عَلَى",
    transliteration: "ala",
    meaning: "On/Upon - Preposition indicating position or authority",
    meaningUrdu: "پر - موقعیت یا اختیار کا اظہار",
    frequency: 897,
    difficulty: 1,
    category: "preposition",
    chapter: 0,
    verse: null,
    rootWord: "ع ل ي",
    examples: ["عَلَى الْأَرْضِ"],
    source: "Classical grammar - Locative/dominative"
  },
  {
    arabic: "مَا",
    transliteration: "ma",
    meaning: "What/That which - Interrogative or relative pronoun",
    meaningUrdu: "کیا/جو - سوالیہ یا موصولی ضمیر",
    frequency: 1150,
    difficulty: 1,
    category: "pronoun",
    chapter: 0,
    verse: null,
    rootWord: "م ا",
    examples: ["مَا فِي السَّمَاوَاتِ"],
    source: "Classical grammar - Multifunctional particle"
  },
  {
    arabic: "لَا",
    transliteration: "la",
    meaning: "No/Not - Negative particle",
    meaningUrdu: "نہیں - منفی حرف",
    frequency: 1455,
    difficulty: 1,
    category: "negation",
    chapter: 0,
    verse: null,
    rootWord: "ل ا",
    examples: ["لَا إِلَهَ إِلَّا اللَّهُ"],
    source: "Classical grammar - Primary negation"
  },
  {
    arabic: "أَنْ",
    transliteration: "an",
    meaning: "That/To - Conjunction introducing purpose or object",
    meaningUrdu: "کہ - مقصد یا مفعول کا تعین",
    frequency: 1178,
    difficulty: 1,
    category: "particle",
    chapter: 0,
    verse: null,
    rootWord: "ا ن",
    examples: ["أَنْ تَعْبُدُوا اللَّهَ"],
    source: "Classical grammar - Masdar particle"
  },
  {
    arabic: "كَانَ",
    transliteration: "kana",
    meaning: "Was/Used to be - Past tense copula",
    meaningUrdu: "تھا - ماضی کا فعل ناقص",
    frequency: 1358,
    difficulty: 1,
    category: "verb",
    chapter: 0,
    verse: null,
    rootWord: "ك و ن",
    examples: ["كَانَ اللَّهُ عَلِيمًا"],
    source: "Classical grammar - Defective verb"
  },
  {
    arabic: "قَالَ",
    transliteration: "qaala",
    meaning: "Said - Past tense verb of speaking",
    meaningUrdu: "کہا - بولنے کا ماضی",
    frequency: 1722,
    difficulty: 1,
    category: "verb",
    chapter: 0,
    verse: null,
    rootWord: "ق و ل",
    examples: ["قَالَ اللَّهُ"],
    source: "Classical lexicons - Basic speech verb"
  },
  {
    arabic: "وَ",
    transliteration: "wa",
    meaning: "And - Coordinating conjunction",
    meaningUrdu: "اور - ربط کا حرف",
    frequency: 12194,
    difficulty: 1,
    category: "conjunction",
    chapter: 0,
    verse: null,
    rootWord: "و",
    examples: ["وَاللَّهُ أَعْلَمُ"],
    source: "Classical grammar - Primary conjunction"
  },

  // Essential divine attributes and concepts
  {
    arabic: "الْعَلِيمُ",
    transliteration: "al-aleem",
    meaning: "The All-Knowing - Divine attribute of complete knowledge",
    meaningUrdu: "جاننے والا - کامل علم کی صفت",
    frequency: 158,
    difficulty: 2,
    category: "attributes",
    chapter: 0,
    verse: null,
    rootWord: "ع ل م",
    examples: ["وَاللَّهُ عَلِيمٌ حَكِيمٌ"],
    source: "Classical theology - Divine attribute"
  },
  {
    arabic: "الْحَكِيمُ",
    transliteration: "al-hakeem",
    meaning: "The All-Wise - Divine attribute of perfect wisdom",
    meaningUrdu: "حکمت والا - کمال حکمت کی صفت",
    frequency: 97,
    difficulty: 2,
    category: "attributes",
    chapter: 0,
    verse: null,
    rootWord: "ح ك م",
    examples: ["عَلِيمٌ حَكِيمٌ"],
    source: "Classical theology - Divine wisdom"
  },
  {
    arabic: "الْقَدِيرُ",
    transliteration: "al-qadeer",
    meaning: "The All-Powerful - Divine attribute of absolute power",
    meaningUrdu: "قادر - مطلق قدرت کی صفت",
    frequency: 45,
    difficulty: 2,
    category: "attributes",
    chapter: 0,
    verse: null,
    rootWord: "ق د ر",
    examples: ["وَاللَّهُ عَلَى كُلِّ شَيْءٍ قَدِيرٌ"],
    source: "Classical theology - Divine omnipotence"
  },
  {
    arabic: "الْغَفُورُ",
    transliteration: "al-ghafoor",
    meaning: "The All-Forgiving - Divine attribute of endless forgiveness",
    meaningUrdu: "بخشنے والا - لامحدود مغفرت کی صفت",
    frequency: 91,
    difficulty: 2,
    category: "attributes",
    chapter: 0,
    verse: null,
    rootWord: "غ ف ر",
    examples: ["وَاللَّهُ غَفُورٌ رَحِيمٌ"],
    source: "Classical theology - Divine mercy"
  },

  // Common verbs and essential vocabulary
  {
    arabic: "يَعْلَمُ",
    transliteration: "ya'lamu",
    meaning: "He knows - Present tense of knowing",
    meaningUrdu: "وہ جانتا ہے - جاننے کا حال",
    frequency: 854,
    difficulty: 1,
    category: "verb",
    chapter: 0,
    verse: null,
    rootWord: "ع ل م",
    examples: ["يَعْلَمُ مَا فِي الْقُلُوبِ"],
    source: "Classical lexicons - Present indicative"
  },
  {
    arabic: "خَلَقَ",
    transliteration: "khalaqa",
    meaning: "Created - Past tense of creation",
    meaningUrdu: "پیدا کیا - تخلیق کا ماضی",
    frequency: 261,
    difficulty: 1,
    category: "verb",
    chapter: 0,
    verse: null,
    rootWord: "خ ل ق",
    examples: ["خَلَقَ الْإِنْسَانَ"],
    source: "Classical lexicons - Divine creation"
  },
  {
    arabic: "جَعَلَ",
    transliteration: "ja'ala",
    meaning: "Made/Appointed - Past tense of making or designating",
    meaningUrdu: "بنایا/مقرر کیا - بنانے یا مقرر کرنے کا ماضی",
    frequency: 359,
    difficulty: 1,
    category: "verb",
    chapter: 0,
    verse: null,
    rootWord: "ج ع ل",
    examples: ["جَعَلَ لَكُمْ"],
    source: "Classical lexicons - Causative action"
  },
  {
    arabic: "الْأَرْضِ",
    transliteration: "al-ard",
    meaning: "The earth - Physical world, ground, land",
    meaningUrdu: "زمین - دنیا، زمین کا ٹکڑا",
    frequency: 461,
    difficulty: 1,
    category: "creation",
    chapter: 0,
    verse: null,
    rootWord: "ا ر ض",
    examples: ["فِي الْأَرْضِ"],
    source: "Classical lexicons - Basic geography"
  },
  {
    arabic: "السَّمَاءِ",
    transliteration: "as-samaa",
    meaning: "The sky/heaven - Celestial realm above",
    meaningUrdu: "آسمان - آسمانی کائنات",
    frequency: 310,
    difficulty: 1,
    category: "creation",
    chapter: 0,
    verse: null,
    rootWord: "س م و",
    examples: ["مِنَ السَّمَاءِ"],
    source: "Classical lexicons - Celestial realm"
  },
  {
    arabic: "النَّاسِ",
    transliteration: "an-naas",
    meaning: "The people - Human beings collectively",
    meaningUrdu: "لوگ - انسانوں کا مجموعہ",
    frequency: 241,
    difficulty: 1,
    category: "social",
    chapter: 0,
    verse: null,
    rootWord: "ن و س",
    examples: ["مِنَ النَّاسِ"],
    source: "Classical lexicons - Human collective"
  },
  {
    arabic: "الْإِنْسَانَ",
    transliteration: "al-insaan",
    meaning: "The human being - Individual person",
    meaningUrdu: "انسان - فرد واحد",
    frequency: 65,
    difficulty: 1,
    category: "social",
    chapter: 0,
    verse: null,
    rootWord: "ا ن س",
    examples: ["خَلَقَ الْإِنْسَانَ"],
    source: "Classical lexicons - Individual human"
  },
  {
    arabic: "الصَّلَاةَ",
    transliteration: "as-salaah",
    meaning: "The prayer - Ritual worship and connection with Allah",
    meaningUrdu: "نماز - اللہ سے رابطے کی عبادت",
    frequency: 99,
    difficulty: 1,
    category: "worship",
    chapter: 0,
    verse: null,
    rootWord: "ص ل و",
    examples: ["أَقِيمُوا الصَّلَاةَ"],
    source: "Islamic terminology - Core worship"
  },
  {
    arabic: "الزَّكَاةَ",
    transliteration: "az-zakaah",
    meaning: "The charity - Obligatory wealth purification",
    meaningUrdu: "زکوٰۃ - مال کی لازمی صفائی",
    frequency: 32,
    difficulty: 2,
    category: "worship",
    chapter: 0,
    verse: null,
    rootWord: "ز ك و",
    examples: ["وَآتُوا الزَّكَاةَ"],
    source: "Islamic terminology - Wealth purification"
  }
];