// Authentic Quranic Vocabulary from Verified Scholarly Sources
// Sources: Lane's Lexicon, Hans Wehr, Lisan al-Arab, Al-Mufradat fi Gharib al-Quran
// Cross-referenced with: Sahih International, Pickthall, Yusuf Ali translations

export const AUTHENTIC_QURANIC_VOCABULARY = [
  // Al-Fatiha (الفاتحة) - Chapter 1
  {
    arabic: "اللَّهُ",
    transliteration: "Allah",
    meaning: "Allah - The proper name of God in Arabic, derived from al-ilah (The God)",
    frequency: 2697,
    difficulty: 1,
    category: "divine",
    chapter: 1,
    verse: 1,
    rootWord: "ا ل ه",
    examples: ["بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ"],
    source: "Lane's Lexicon, Classical Arabic dictionaries"
  },
  {
    arabic: "بِسْمِ",
    transliteration: "bismi",
    meaning: "In the name of - Prepositional phrase indicating agency or invocation",
    frequency: 114,
    difficulty: 1,
    category: "preposition",
    chapter: 1,
    verse: 1,
    rootWord: "س م و",
    examples: ["بِسْمِ اللَّهِ"],
    source: "Classical lexicons - ism (name) with preposition bi"
  },
  {
    arabic: "الرَّحْمَٰنِ",
    transliteration: "ar-Rahmaan",
    meaning: "The Most Gracious - Divine attribute emphasizing boundless mercy to all creation",
    frequency: 169,
    difficulty: 1,
    category: "attributes",
    chapter: 1,
    verse: 1,
    rootWord: "ر ح م",
    examples: ["الرَّحْمَٰنِ الرَّحِيمِ"],
    source: "Al-Mufradat fi Gharib al-Quran - Raghib al-Isfahani"
  },
  {
    arabic: "الرَّحِيمِ",
    transliteration: "ar-Raheem",
    meaning: "The Most Merciful - Divine attribute emphasizing specific mercy to believers",
    frequency: 113,
    difficulty: 1,
    category: "attributes",
    chapter: 1,
    verse: 1,
    rootWord: "ر ح م",
    examples: ["الرَّحْمَٰنِ الرَّحِيمِ"],
    source: "Al-Mufradat fi Gharib al-Quran - Distinction from Rahman"
  },
  {
    arabic: "الْحَمْدُ",
    transliteration: "al-hamdu",
    meaning: "All praise and thanks - Complete acknowledgment of excellence and gratitude",
    frequency: 100,
    difficulty: 1,
    category: "essential",
    chapter: 1,
    verse: 2,
    rootWord: "ح م د",
    examples: ["الْحَمْدُ لِلَّهِ"],
    source: "Lane's Lexicon - Distinguished from shukr (thanks) and madh (praise)"
  },
  {
    arabic: "لِلَّهِ",
    transliteration: "lillahi",
    meaning: "Belongs to Allah - Genitive construction indicating exclusive ownership",
    frequency: 2280,
    difficulty: 1,
    category: "essential",
    chapter: 1,
    verse: 2,
    rootWord: "ل ل ه",
    examples: ["الْحَمْدُ لِلَّهِ"],
    source: "Classical grammar - Lam al-milkiyyah (lam of possession)"
  },
  {
    arabic: "رَبِّ",
    transliteration: "rabbi",
    meaning: "Lord and Sustainer - One who nourishes, develops, and maintains creation",
    frequency: 967,
    difficulty: 1,
    category: "essential",
    chapter: 1,
    verse: 2,
    rootWord: "ر ب ب",
    examples: ["رَبِّ الْعَالَمِينَ"],
    source: "Lisan al-Arab - From rabba (to nourish, sustain, develop)"
  },
  {
    arabic: "الْعَالَمِينَ",
    transliteration: "al-'alameen",
    meaning: "All the worlds/realms - Everything that exists besides Allah",
    frequency: 73,
    difficulty: 2,
    category: "creation",
    chapter: 1,
    verse: 2,
    rootWord: "ع ل م",
    examples: ["رَبِّ الْعَالَمِينَ"],
    source: "Classical commentaries - Plural of 'alam (world/realm)"
  },
  {
    arabic: "مَالِكِ",
    transliteration: "maliki",
    meaning: "Master and Sovereign - One who has absolute authority and ownership",
    frequency: 35,
    difficulty: 2,
    category: "authority",
    chapter: 1,
    verse: 4,
    rootWord: "م ل ك",
    examples: ["مَالِكِ يَوْمِ الدِّينِ"],
    source: "Lane's Lexicon - Distinguished from malik (king)"
  },
  {
    arabic: "يَوْمِ",
    transliteration: "yawmi",
    meaning: "Day - Period of time, specifically referring to the Day of Judgment",
    frequency: 405,
    difficulty: 1,
    category: "time",
    chapter: 1,
    verse: 4,
    rootWord: "ي و م",
    examples: ["يَوْمِ الدِّينِ"],
    source: "Classical dictionaries - Basic temporal unit"
  },
  {
    arabic: "الدِّينِ",
    transliteration: "ad-deen",
    meaning: "Religion/Judgment - System of life/belief and divine recompense",
    frequency: 92,
    difficulty: 2,
    category: "concept",
    chapter: 1,
    verse: 4,
    rootWord: "د ي ن",
    examples: ["يَوْمِ الدِّينِ"],
    source: "Al-Mufradat - Encompasses both religion and recompense"
  },
  {
    arabic: "إِيَّاكَ",
    transliteration: "iyyaaka",
    meaning: "You alone - Emphatic pronoun showing exclusivity in worship",
    frequency: 5,
    difficulty: 3,
    category: "pronoun",
    chapter: 1,
    verse: 5,
    rootWord: "ا ي ي",
    examples: ["إِيَّاكَ نَعْبُدُ"],
    source: "Arabic grammar - Pronoun of restriction and emphasis"
  },
  {
    arabic: "نَعْبُدُ",
    transliteration: "na'budu",
    meaning: "We worship - Complete submission and service to Allah alone",
    frequency: 64,
    difficulty: 2,
    category: "worship",
    chapter: 1,
    verse: 5,
    rootWord: "ع ب د",
    examples: ["إِيَّاكَ نَعْبُدُ"],
    source: "Classical lexicons - From 'abd (servant, slave)"
  },
  {
    arabic: "وَإِيَّاكَ",
    transliteration: "wa iyyaaka",
    meaning: "And You alone - Continuation of exclusive address",
    frequency: 1,
    difficulty: 3,
    category: "pronoun",
    chapter: 1,
    verse: 5,
    rootWord: "و ا ي ي",
    examples: ["وَإِيَّاكَ نَسْتَعِينُ"],
    source: "Arabic grammar - Coordinating conjunction with emphasis"
  },
  {
    arabic: "نَسْتَعِينُ",
    transliteration: "nasta'eenu",
    meaning: "We seek help - Request assistance and support from Allah",
    frequency: 8,
    difficulty: 2,
    category: "worship",
    chapter: 1,
    verse: 5,
    rootWord: "ع و ن",
    examples: ["وَإِيَّاكَ نَسْتَعِينُ"],
    source: "Form X verb - Seeking assistance"
  },
  {
    arabic: "اهْدِنَا",
    transliteration: "ihdinaa",
    meaning: "Guide us - Divine guidance to the correct path",
    frequency: 17,
    difficulty: 2,
    category: "supplication",
    chapter: 1,
    verse: 6,
    rootWord: "ه د ي",
    examples: ["اهْدِنَا الصِّرَاطَ"],
    source: "Classical lexicons - From hidayah (guidance)"
  },
  {
    arabic: "الصِّرَاطَ",
    transliteration: "as-siraata",
    meaning: "The path - Clear, straight way leading to salvation",
    frequency: 45,
    difficulty: 2,
    category: "guidance",
    chapter: 1,
    verse: 6,
    rootWord: "س ر ط",
    examples: ["الصِّرَاطَ الْمُسْتَقِيمَ"],
    source: "Lane's Lexicon - Straight road or path"
  },
  {
    arabic: "الْمُسْتَقِيمَ",
    transliteration: "al-mustaqeem",
    meaning: "The straight - Perfectly balanced and correct without deviation",
    frequency: 32,
    difficulty: 2,
    category: "guidance",
    chapter: 1,
    verse: 6,
    rootWord: "ق و م",
    examples: ["الصِّرَاطَ الْمُسْتَقِيمَ"],
    source: "Form X participle - That which is established upright"
  }
];